// Code generated by github.com/hanpama/pgmg. DO NOT EDIT.
package customer_customer_demo

func Insert(vss ...Values) Query {
	return query{InsertSQL, []interface{}{string(mustMarshalJSON(vss))}}
}
func InsertReturning(vss ...Values) Query {
	return query{InsertReturningSQL, []interface{}{string(mustMarshalJSON(vss))}}
}
func Select(k key) Query {
	return k.selectSQL()
}
func Update(k key, args ...attribute) Query {
	return k.updateSQL(args...)
}
func Delete(k key) Query {
	return k.deleteSQL()
}

const (
	InsertSQL = `
		INSERT INTO "public"."customer_customer_demo" (
			"customer_id",
			"customer_type_id"
		)
		SELECT
			"customer_id",
			"customer_type_id"
		FROM json_populate_recordset(null::"public"."customer_customer_demo", $1)`
	InsertReturningSQL = `
		INSERT INTO "public"."customer_customer_demo" (
			"customer_id",
			"customer_type_id"
		)
		SELECT
			"customer_id",
			"customer_type_id"
		FROM json_populate_recordset(null::"public"."customer_customer_demo", $1)
		RETURNING
			"customer_id",
			"customer_type_id"`
)

func (k PkCustomerCustomerDemo) selectSQL() Query {
	return selectPkCustomerCustomerDemoQuery{k}
}
func (k PkCustomerCustomerDemo) updateSQL(args ...attribute) Query {
	return query{UpdatePkCustomerCustomerDemo, []interface{}{
		k.CustomerID,
		k.CustomerTypeID,
		string(mustMarshalJSON(Values(args))),
	}}
}
func (k PkCustomerCustomerDemo) deleteSQL() Query {
	return query{DeletePkCustomerCustomerDemo, []interface{}{
		k.CustomerID,
		k.CustomerTypeID,
	}}
}

const (
	SelectPkCustomerCustomerDemo = `
		SELECT 
			"customer_id",
			"customer_type_id"
		FROM "public"."customer_customer_demo" WHERE ("customer_id", "customer_type_id") = ($1, $2) LIMIT 1`
	UpdatePkCustomerCustomerDemo = `
		UPDATE "public"."customer_customer_demo" __ut__
		SET "customer_id" = COALESCE(__ch__."customer_id", __ut__."customer_id"),
			"customer_type_id" = COALESCE(__ch__."customer_type_id", __ut__."customer_type_id")
		FROM (SELECT * FROM json_populate_record(null::"public"."customer_customer_demo", $2)) __ch__
		WHERE (__ut__."customer_id", __ut__."customer_type_id") = ($1, $2)`
	DeletePkCustomerCustomerDemo = `
		DELETE FROM "public"."customer_customer_demo"
		WHERE ("customer_id", "customer_type_id") = ($1, $2)`
)

type selectPkCustomerCustomerDemoQuery struct{ key PkCustomerCustomerDemo }

func (q selectPkCustomerCustomerDemoQuery) SQL() string { return SelectPkCustomerCustomerDemo }
func (q selectPkCustomerCustomerDemoQuery) Args() []interface{} {
	return []interface{}{q.key.CustomerID, q.key.CustomerTypeID}
}

type key interface {
	selectSQL() Query
	updateSQL(args ...attribute) Query
	deleteSQL() Query
}

type Query interface {
	SQL() string
	Args() []interface{}
}

type query struct {
	sql  string
	args []interface{}
}

func (q query) SQL() string         { return q.sql }
func (q query) Args() []interface{} { return q.args }
