// Code generated by github.com/hanpama/pgmg. DO NOT EDIT.
package territories

import (
	"encoding/json"
)

type Record struct {
	TerritoryID          string `json:"territory_id"`
	TerritoryDescription string `json:"territory_description"`
	RegionID             int16  `json:"region_id"`
}

type PkTerritories struct {
	TerritoryID string `json:"territory_id"`
}

type TerritoryID string
type TerritoryDescription string
type RegionID int16

func (r *Record) Receive() []interface{} {
	return []interface{}{
		&r.TerritoryID,
		&r.TerritoryDescription,
		&r.RegionID,
	}
}

type Recordset []Record

func (rs *Recordset) ReceiveNext() []interface{} {
	*rs = append(*rs, Record{})
	return (*rs)[len(*rs)-1].Receive()
}

type Values []attribute

func InputValues(
	territoryID TerritoryID,
	territoryDescription TerritoryDescription,
	regionID RegionID,
	attrs ...attribute,
) Values {
	return append(Values{
		territoryID,
		territoryDescription,
		regionID,
	}, attrs...)
}
func (vs Values) ApplyTo(r *Record) {
	for _, v := range vs {
		v.ApplyTo(r)
	}
}

func (vs Values) MarshalJSON() (b []byte, err error) {
	r := make(map[string]interface{})
	for _, v := range vs {
		r[v.Column()] = v.Value()
	}
	return json.Marshal(r)
}

type attribute interface {
	ApplyTo(*Record)
	Column() string
	Value() interface{}
}

func (v TerritoryID) ApplyTo(r *Record)           { r.TerritoryID = (string)(v) }
func (v TerritoryID) Column() string              { return "territory_id" }
func (v TerritoryID) Value() interface{}          { return (string)(v) }
func (v TerritoryDescription) ApplyTo(r *Record)  { r.TerritoryDescription = (string)(v) }
func (v TerritoryDescription) Column() string     { return "territory_description" }
func (v TerritoryDescription) Value() interface{} { return (string)(v) }
func (v RegionID) ApplyTo(r *Record)              { r.RegionID = (int16)(v) }
func (v RegionID) Column() string                 { return "region_id" }
func (v RegionID) Value() interface{}             { return (int16)(v) }

func mustMarshalJSON(v interface{}) []byte {
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return b
}
