// Code generated by github.com/hanpama/pgmg. DO NOT EDIT.
package professor

func Insert(vss ...Values) Query {
	return Query{InsertSQL, []interface{}{string(mustMarshalJSON(vss))}}
}
func InsertReturning(vss ...Values) Query {
	return Query{InsertReturningSQL, []interface{}{string(mustMarshalJSON(vss))}}
}
func Select(k key) Query {
	return k.selectSQL()
}
func Update(k key, args ...attribute) Query {
	return k.updateSQL(args...)
}
func Delete(k key) Query {
	return k.deleteSQL()
}

const (
	InsertSQL = `
		INSERT INTO "wise"."professor" (
			"id",
			"family_name",
			"given_name"
		)
		SELECT
			COALESCE("id", nextval('wise.professor_id_seq'::regclass)),
			"family_name",
			"given_name"
		FROM json_populate_recordset(null::"wise"."professor", $1)`
	InsertReturningSQL = `
		INSERT INTO "wise"."professor" (
			"id",
			"family_name",
			"given_name"
		)
		SELECT
			COALESCE("id", nextval('wise.professor_id_seq'::regclass)),
			"family_name",
			"given_name"
		FROM json_populate_recordset(null::"wise"."professor", $1)
		RETURNING
			"id",
			"family_name",
			"given_name"`
)

func (k ProfessorPkey) selectSQL() Query {
	return Query{SelectProfessorPkey, []interface{}{
		k.ID,
	}}
}
func (k ProfessorPkey) updateSQL(args ...attribute) Query {
	return Query{UpdateProfessorPkey, []interface{}{
		k.ID,
		string(mustMarshalJSON(Values(args))),
	}}
}
func (k ProfessorPkey) deleteSQL() Query {
	return Query{DeleteProfessorPkey, []interface{}{
		k.ID,
	}}
}

const (
	SelectProfessorPkey = `
		SELECT * FROM "wise"."professor" WHERE ("id") = ($1) LIMIT 1
		`
	UpdateProfessorPkey = `
		UPDATE "wise"."professor" __ut__
		SET "id" = COALESCE(__ch__."id", __ut__."id"),
			"family_name" = COALESCE(__ch__."family_name", __ut__."family_name"),
			"given_name" = COALESCE(__ch__."given_name", __ut__."given_name")
		FROM (SELECT * FROM json_populate_record(null::"wise"."professor", $2)) __ch__
		WHERE (__ut__."id") = ($1)`
	DeleteProfessorPkey = `
		DELETE FROM "wise"."professor"
		WHERE ("id") = ($1)`
)

type key interface {
	selectSQL() Query
	updateSQL(args ...attribute) Query
	deleteSQL() Query
}

type Query struct {
	sql  string
	args []interface{}
}

func (q Query) SQL() string         { return q.sql }
func (q Query) Args() []interface{} { return q.args }
