// Code generated by github.com/hanpama/pgmg. DO NOT EDIT.
package region

func Insert(vss ...Values) Query {
	return Query{InsertSQL, []interface{}{string(mustMarshalJSON(vss))}}
}
func InsertReturning(vss ...Values) Query {
	return Query{InsertReturningSQL, []interface{}{string(mustMarshalJSON(vss))}}
}
func Select(k key) Query {
	return k.selectSQL()
}
func Update(k key, args ...attribute) Query {
	return k.updateSQL(args...)
}
func Delete(k key) Query {
	return k.deleteSQL()
}

const (
	InsertSQL = `
		INSERT INTO "region"
		SELECT * FROM json_populate_recordset(null::"region", $1) `
	InsertReturningSQL = `
		INSERT INTO "region"
		SELECT * FROM json_populate_recordset(null::"region", $1)
		RETURNING *`
)

func (k PkRegion) selectSQL() Query {
	return Query{SelectPkRegion, []interface{}{
		k.RegionID,
	}}
}
func (k PkRegion) updateSQL(args ...attribute) Query {
	return Query{UpdatePkRegion, []interface{}{
		k.RegionID,
		string(mustMarshalJSON(Values(args))),
	}}
}
func (k PkRegion) deleteSQL() Query {
	return Query{DeletePkRegion, []interface{}{
		k.RegionID,
	}}
}

const (
	SelectPkRegion = `
		SELECT * FROM "region" WHERE ("region"."region_id") = ($1) LIMIT 1
		`
	UpdatePkRegion = `
		UPDATE "region"
		SET "region_id" = COALESCE(_ch."region_id", "region"."region_id"),
			"region_description" = COALESCE(_ch."region_description", "region"."region_description")
		FROM (SELECT * FROM json_populate_record(null::"region", $2)) _ch
		WHERE ("region"."region_id") = ($1)`
	DeletePkRegion = `
		DELETE FROM "region"
		WHERE ("region"."region_id") = ($1)`
)

type key interface {
	selectSQL() Query
	updateSQL(args ...attribute) Query
	deleteSQL() Query
}

type Query struct {
	sql  string
	args []interface{}
}

func (q Query) SQL() string         { return q.sql }
func (q Query) Args() []interface{} { return q.args }
