// Code generated by github.com/hanpama/pgmg. DO NOT EDIT.
package tables

import (
	"context"
	"encoding/json"
)

// CampaignRow represents a row for table "campaign"
type CampaignRow struct {
	v CampaignData
}

type CampaignData struct {
	ID      string  `json:"id"`
	PopName *string `json:"pop_name"`
	PopYear *int32  `json:"pop_year"`
}

func NewCampaignRow(data CampaignData) *CampaignRow {
	return &CampaignRow{data}
}

func NewCampaignRows(data ...CampaignData) CampaignRows {
	rows := make(CampaignRows, len(data))
	for i, d := range data {
		rows[i] = NewCampaignRow(d)
	}
	return rows
}

// GetID gets value of column "id" from "campaign" row
func (r *CampaignRow) GetID() string { return r.v.ID }

// SetID sets value of column "id" in "campaign" row
func (r *CampaignRow) SetID(id string) { r.v.ID = id }

// GetPopName gets value of column "pop_name" from "campaign" row
func (r *CampaignRow) GetPopName() string { return *r.v.PopName }

// SetPopName sets value of column "pop_name" in "campaign" row
func (r *CampaignRow) SetPopName(popName string) { r.v.PopName = &popName }

// ClearPopName sets value of column "pop_name" null in "campaign" row
func (r *CampaignRow) ClearPopName() { r.v.PopName = nil }

// HasValidPopName checks to value of column "pop_name" is not null
func (r *CampaignRow) HasValidPopName() bool { return r.v.PopName != nil }

// GetPopYear gets value of column "pop_year" from "campaign" row
func (r *CampaignRow) GetPopYear() int32 { return *r.v.PopYear }

// SetPopYear sets value of column "pop_year" in "campaign" row
func (r *CampaignRow) SetPopYear(popYear int32) { r.v.PopYear = &popYear }

// ClearPopYear sets value of column "pop_year" null in "campaign" row
func (r *CampaignRow) ClearPopYear() { r.v.PopYear = nil }

// HasValidPopYear checks to value of column "pop_year" is not null
func (r *CampaignRow) HasValidPopYear() bool { return r.v.PopYear != nil }

// CampaignID represents key defined by PRIMARY KEY constraint "campaign_pkey" for table "campaign"
type CampaignID struct {
	ID string `json:"id"`
}

func (r *CampaignRow) KeyID() CampaignID {
	return CampaignID{r.GetID()}
}

// CampaignRows represents multiple rows for table "campaign"
type CampaignRows []*CampaignRow

// CampaignIDKeyset is a set of key CampaignID
type CampaignIDKeyset map[CampaignID]struct{}

func (rs CampaignRows) KeyID() (keys CampaignIDKeyset) {
	keys = make(CampaignIDKeyset)
	for _, r := range rs {
		keys[r.KeyID()] = struct{}{}
	}
	return keys
}

func (r *CampaignRow) RefPopNamePopYear() PopNameYear {
	return PopNameYear{r.GetPopName(), r.GetPopYear()}
}

func (rs CampaignRows) RefPopNamePopYear() (keys PopNameYearKeyset) {
	keys = make(PopNameYearKeyset)
	for _, r := range rs {
		keys[r.RefPopNamePopYear()] = struct{}{}
	}
	return keys
}

// NewCampaignTable(h SQLHandle) creates new CampaignTable
func NewCampaignTable(h SQLHandle) *CampaignTable {
	return &CampaignTable{h}
}

// CampaignTable provides access methods for table "campaign"
type CampaignTable struct {
	h SQLHandle
}

func (t *CampaignTable) Find(ctx context.Context, filter CampaignValues) (CampaignRows, error) {
	return FindCampaignRows(ctx, t.h, filter)
}

func (t *CampaignTable) Count(ctx context.Context, filter CampaignValues) (int, error) {
	return CountCampaignRows(ctx, t.h, filter)
}

func (t *CampaignTable) Update(ctx context.Context, changeset, filter CampaignValues) (int64, error) {
	return UpdateCampaignRows(ctx, t.h, changeset, filter)
}

func (t *CampaignTable) Insert(ctx context.Context, rows ...*CampaignRow) (int, error) {
	return InsertReturningCampaignRows(ctx, t.h, rows...)
}

func (t *CampaignTable) Delete(ctx context.Context, filter CampaignValues) (int64, error) {
	return DeleteCampaignRows(ctx, t.h, filter)
}

func (t *CampaignTable) Save(ctx context.Context, rows ...*CampaignRow) error {
	return SaveReturningCampaignRows(ctx, t.h, rows...)
}

func (t *CampaignTable) GetByID(ctx context.Context, keys ...CampaignID) (CampaignRows, error) {
	return GetCampaignRowsByID(ctx, t.h, keys...)
}

func (t *CampaignTable) UpdateByID(ctx context.Context, changeset CampaignValues, keys ...CampaignID) (int64, error) {
	return UpdateCampaignRowsByID(ctx, t.h, changeset, keys...)
}

func (t *CampaignTable) DeleteByID(ctx context.Context, keys ...CampaignID) (int64, error) {
	return DeleteCampaignRowsByID(ctx, t.h, keys...)
}

type CampaignValues struct {
	ID      *string `json:"id"`
	PopName *string `json:"pop_name"`
	PopYear *int32  `json:"pop_year"`
}

// InsertCampaignRows inserts the rows into table "campaign"
func InsertCampaignRows(ctx context.Context, db SQLHandle, rows ...*CampaignRow) (affected int64, err error) {
	affected, err = execWithJSONArgs(ctx, db, sqlInsertCampaignRows, rows)
	if err != nil {
		return affected, formatError("InsertCampaignRows", err)
	}
	return affected, nil
}

// InsertReturningCampaignRows inserts the rows into table "campaign" and returns the rows.
func InsertReturningCampaignRows(ctx context.Context, db SQLHandle, inputs ...*CampaignRow) (affected int, err error) {
	rows := CampaignRows(inputs)
	affected, err = queryWithJSONArgs(ctx, db, rows.ReceiveRows, sqlInsertReturningCampaignRows, rows)
	if err != nil {
		return affected, formatError("InsertReturningCampaignRows", err)
	}
	return affected, nil
}

// FindCampaignRows finds the rows matching the condition from table "campaign"
func FindCampaignRows(ctx context.Context, db SQLHandle, cond CampaignValues) (rows CampaignRows, err error) {
	if _, err = queryWithJSONArgs(ctx, db, rows.ReceiveRows, sqlFindCampaignRows, cond); err != nil {
		return nil, err
	}
	return rows, nil
}

// DeleteCampaignRows deletes the rows matching the condition from table "campaign"
func DeleteCampaignRows(ctx context.Context, db SQLHandle, cond CampaignValues) (afftected int64, err error) {
	return execWithJSONArgs(ctx, db, sqlDeleteCampaignRows, cond)
}

func UpdateCampaignRows(ctx context.Context, db SQLHandle, changeset, filter CampaignValues) (afftected int64, err error) {
	return execWithJSONArgs(ctx, db, sqlUpdateCampaignRows, changeset, filter)
}

// CountCampaignRows counts the number of rows matching the condition from table "campaign"
func CountCampaignRows(ctx context.Context, db SQLHandle, cond CampaignValues) (count int, err error) {
	if _, err = queryWithJSONArgs(ctx, db, func(int) []interface{} { return []interface{}{&count} }, sqlCountCampaignRows, cond); err != nil {
		return 0, err
	}
	return count, nil
}

// SaveCampaignRows upserts the given rows for table "campaign" checking uniqueness by contstraint "campaign_pkey"
func SaveCampaignRows(ctx context.Context, db SQLHandle, rows ...*CampaignRow) (err error) {
	numRows, err := execWithJSONArgs(ctx, db, sqlSaveCampaignRows, rows)
	if err != nil {
		return formatError("Save", err)
	}
	if int64(len(rows)) != numRows {
		return formatError("Save", ErrUnexpectedRowNumberAffected)
	}
	return nil
}

// SaveReturningCampaignRows upserts the given rows for table "campaign" checking uniqueness by contstraint "campaign_pkey"
// It returns the new values and scan them into given row references.
func SaveReturningCampaignRows(ctx context.Context, db SQLHandle, inputs ...*CampaignRow) (err error) {
	rows := CampaignRows(inputs)
	numRows, err := queryWithJSONArgs(ctx, db, rows.ReceiveRows, sqlSaveReturningCampaignRows, rows)
	if err != nil {
		return formatError("SaveReturning", err)
	}
	if len(rows) != numRows {
		return formatError("SaveReturning", ErrUnexpectedRowNumberAffected)
	}
	return nil
}

// GetCampaignRowsByID gets matching rows for given ID keys from table "campaign"
func GetCampaignRowsByID(ctx context.Context, db SQLHandle, keys ...CampaignID) (rows CampaignRows, err error) {
	rows = make(CampaignRows, len(keys))
	if _, err = queryWithJSONArgs(ctx, db, rows.ReceiveRows, sqlGetCampaignRowsByID, keys); err != nil {
		return nil, formatError("GetCampaignRowsByID", err)
	}
	for i := 0; i < len(keys); i++ {
		if rows[i] == nil {
			break
		} else if rows[i].KeyID() != keys[i] {
			copy(rows[i+1:], rows[i:])
			rows[i] = nil
		}
	}
	return rows, nil
}

// DeleteCampaignRowsByID deletes matching rows by CampaignID keys from table "campaign"
func DeleteCampaignRowsByID(ctx context.Context, db SQLHandle, keys ...CampaignID) (numRows int64, err error) {
	numRows, err = execWithJSONArgs(ctx, db, sqlDeleteCampaignRowsByID, keys)
	if err != nil {
		return numRows, formatError("DeleteByID", err)
	}
	return numRows, nil
}

// UpdateCampaignRowsByID deletes matching rows by CampaignID keys from table "campaign"
func UpdateCampaignRowsByID(ctx context.Context, db SQLHandle, changeset CampaignValues, keys ...CampaignID) (numRows int64, err error) {
	numRows, err = execWithJSONArgs(ctx, db, sqlUpdateCampaignRowsByID, changeset, keys)
	if err != nil {
		return numRows, formatError("UpdateByID", err)
	}
	return numRows, nil
}

func (r *CampaignRow) ReceiveRow() []interface{} {
	return []interface{}{&r.v.ID, &r.v.PopName, &r.v.PopYear}
}

// ReceiveRows returns pointer slice to receive data for the row on index i
func (rs *CampaignRows) ReceiveRows(i int) []interface{} {
	if cap(*rs) <= i {
		source := *rs
		*rs = make(CampaignRows, i+1)
		copy(*rs, source)
	}
	if (*rs)[i] == nil {
		(*rs)[i] = new(CampaignRow)
	}
	return (*rs)[i].ReceiveRow()
}

func (r *CampaignRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(r.v)
}

func (keyset CampaignIDKeyset) Keys() (keys []CampaignID) {
	for k := range keyset {
		keys = append(keys, k)
	}
	return keys
}

func (keyset CampaignIDKeyset) Add(keys ...CampaignID) {
	for _, k := range keys {
		keyset[k] = struct{}{}
	}
}

func (keyset CampaignIDKeyset) Remove(keys ...CampaignID) {
	for _, k := range keys {
		delete(keyset, k)
	}
}

var (
	sqlFindCampaignRows = `
		WITH __f AS (SELECT "id", "pop_name", "pop_year" FROM json_populate_record(null::"wise"."campaign", $1))
		SELECT __t.id, __t.pop_name, __t.pop_year
		FROM "wise"."campaign" AS __t
		WHERE ((SELECT __f."id" IS NULL FROM __f) OR (SELECT __f."id" = __t."id" FROM __f))
			AND ((SELECT __f."pop_name" IS NULL FROM __f) OR (SELECT __f."pop_name" = __t."pop_name" FROM __f))
			AND ((SELECT __f."pop_year" IS NULL FROM __f) OR (SELECT __f."pop_year" = __t."pop_year" FROM __f))`
	sqlCountCampaignRows = `
		WITH __f AS (SELECT "id", "pop_name", "pop_year" FROM json_populate_record(null::"wise"."campaign", $1))
		SELECT count(*) FROM "wise"."campaign" AS __t
		WHERE ((SELECT __f."id" IS NULL FROM __f) OR (SELECT __f."id" = __t."id" FROM __f))
			AND ((SELECT __f."pop_name" IS NULL FROM __f) OR (SELECT __f."pop_name" = __t."pop_name" FROM __f))
			AND ((SELECT __f."pop_year" IS NULL FROM __f) OR (SELECT __f."pop_year" = __t."pop_year" FROM __f))`
	sqlReturningCampaignRows = `
		RETURNING "id", "pop_name", "pop_year"`
	sqlInsertCampaignRows = `
		WITH __v AS (SELECT * FROM json_populate_recordset(null::"wise"."campaign", $1))
		INSERT INTO "wise"."campaign" AS __t ("id", "pop_name", "pop_year")
		SELECT 
			__v."id", 
			__v."pop_name", 
			__v."pop_year" FROM __v`
	sqlInsertReturningCampaignRows = sqlInsertCampaignRows + sqlReturningCampaignRows
	sqlDeleteCampaignRows          = `
		DELETE FROM "wise"."campaign" AS __t
		WHERE TRUE
			AND (($1::json->>'id' IS NULL) OR CAST($1::json->>'id' AS uuid) = __t."id")
			AND (($1::json->>'pop_name' IS NULL) OR CAST($1::json->>'pop_name' AS text) = __t."pop_name")
			AND (($1::json->>'pop_year' IS NULL) OR CAST($1::json->>'pop_year' AS integer) = __t."pop_year")`
	sqlDeleteReturningCampaignRows = sqlDeleteCampaignRows + sqlReturningCampaignRows
	sqlUpdateCampaignRows          = `
		WITH __v AS (SELECT * FROM json_populate_record(null::"wise"."campaign", $1)),
			__f AS (SELECT * FROM json_populate_record(null::"wise"."campaign", $2))
		UPDATE "wise"."campaign" AS __t
		SET ("id", "pop_name", "pop_year") = (SELECT 
			COALESCE(__v."id", __t."id"), 
			COALESCE(__v."pop_name", __t."pop_name"), 
			COALESCE(__v."pop_year", __t."pop_year") FROM __v)
		WHERE ((SELECT __f."id" IS NULL FROM __f) OR (SELECT __f."id" = __t."id" FROM __f))
			AND ((SELECT __f."pop_name" IS NULL FROM __f) OR (SELECT __f."pop_name" = __t."pop_name" FROM __f))
			AND ((SELECT __f."pop_year" IS NULL FROM __f) OR (SELECT __f."pop_year" = __t."pop_year" FROM __f))`
	sqlUpdateReturningCampaignRows = sqlUpdateCampaignRows + sqlReturningCampaignRows
	sqlReplaceCampaignRows         = `
		WITH __v AS (SELECT * FROM json_populate_recordset(null::"wise"."campaign", $1))
		UPDATE "wise"."campaign" AS __t
			SET ("id", "pop_name", "pop_year") = (SELECT 
				COALESCE(__v."id", __t."id"), 
				COALESCE(__v."pop_name", __t."pop_name"), 
				COALESCE(__v."pop_year", __t."pop_year")
			FROM __v WHERE __v."id" = __t."id")
		FROM __v WHERE __v."id" = __t."id"`
	sqlReplaceReturningCampaignRows = sqlReplaceCampaignRows + sqlReturningCampaignRows
	sqlSaveCampaignRows             = `
		WITH __v AS (SELECT * FROM json_populate_recordset(null::"wise"."campaign", $1))
		INSERT INTO "wise"."campaign" AS __t ("id", "pop_name", "pop_year")
		SELECT 
			__v."id", 
			__v."pop_name", 
			__v."pop_year" FROM __v
		ON CONFLICT ("id") DO UPDATE
		SET ("id", "pop_name", "pop_year") = (
			SELECT "id", "pop_name", "pop_year" FROM __v
			WHERE __v."id" = __t."id"
		)`
	sqlSaveReturningCampaignRows = sqlSaveCampaignRows + sqlReturningCampaignRows
	sqlGetCampaignRowsByID       = `
		WITH __key AS (SELECT ROW_NUMBER() over () __idx, "id" FROM json_populate_recordset(null::"wise"."campaign", $1))
		SELECT "id", "pop_name", "pop_year"
		FROM __key JOIN "wise"."campaign" AS __t USING ("id")
		ORDER BY __idx`
	sqlUpdateCampaignRowsByID = `
		WITH __v AS (SELECT * FROM json_populate_record(null::"wise"."campaign", $1)),
		  __key AS (SELECT id FROM json_populate_recordset(null::"wise"."campaign", $2))
		UPDATE "wise"."campaign" AS __t
		SET ("id", "pop_name", "pop_year") = (SELECT
			COALESCE(__v."id", __t."id"), 
			COALESCE(__v."pop_name", __t."pop_name"), 
			COALESCE(__v."pop_year", __t."pop_year")
		FROM __v)
		FROM __key WHERE (__key."id" = __t."id")`
	sqlDeleteCampaignRowsByID = `
		WITH __key AS (SELECT id FROM json_populate_recordset(null::"wise"."campaign", $1))
		DELETE FROM "wise"."campaign" AS __t USING __key WHERE (__key."id" = __t."id")`
	sqlDeleteReturningCampaignRowsByID = sqlDeleteCampaignRowsByID + sqlReturningCampaignRows
)
