// Code generated by github.com/hanpama/pgmg. DO NOT EDIT.
package wise

import (
	"encoding/json"

	"github.com/hanpama/pgmg/dsl"
)

type semesterTable struct {
	dsl.TableReference
	ID     dsl.ColumnReference
	Year   dsl.ColumnReference
	Season dsl.ColumnReference
}

func newSemesterTable(alias string) *semesterTable {
	table := dsl.TableReference{TableSchema: `wise`, TableName: `semester`, Alias: alias}
	return &semesterTable{
		table,
		dsl.ColumnReference{TableReference: table, ColumnName: "id"},
		dsl.ColumnReference{TableReference: table, ColumnName: "year"},
		dsl.ColumnReference{TableReference: table, ColumnName: "season"},
	}
}

// Semester represents table semester
var Semester = newSemesterTable("")

func (t *semesterTable) As(alias string) *semesterTable { return newSemesterTable(alias) }
func (t *semesterTable) AllColumns() []interface{} {
	return []interface{}{t.ID, t.Year, t.Season}
}

type semesterColumnValue interface {
	semesterColumn() string
	semesterValue() interface{}
}

type SemesterValues []semesterColumnValue

func (t *semesterTable) Input(
	year semesterTableYear,
	season semesterTableSeason,
	optional ...semesterColumnValue,
) SemesterValues {
	return append(SemesterValues{
		year,
		season,
	}, optional...)
}

func (vs SemesterValues) MarshalJSON() (b []byte, err error) {
	r := make(map[string]interface{})
	for _, v := range vs {
		r[v.semesterColumn()] = v.semesterValue()
	}
	return json.Marshal(r)
}

func (t *semesterTable) NewID(val int32) semesterTableID          { return semesterTableID(val) }
func (t *semesterTable) NewYear(val int32) semesterTableYear      { return semesterTableYear(val) }
func (t *semesterTable) NewSeason(val string) semesterTableSeason { return semesterTableSeason(val) }

type semesterTableID int32
type semesterTableYear int32
type semesterTableSeason string

func (semesterTableID) semesterColumn() string           { return "id" }
func (v semesterTableID) semesterValue() interface{}     { return (int32)(v) }
func (semesterTableYear) semesterColumn() string         { return "year" }
func (v semesterTableYear) semesterValue() interface{}   { return (int32)(v) }
func (semesterTableSeason) semesterColumn() string       { return "season" }
func (v semesterTableSeason) semesterValue() interface{} { return (string)(v) }

type SemesterRow struct {
	ID     int32  `json:"id"`
	Year   int32  `json:"year"`
	Season string `json:"season"`
}

func (r *SemesterRow) Receive() []interface{} {
	return []interface{}{&r.ID, &r.Year, &r.Season}
}

type SemesterRows []SemesterRow

func (rs *SemesterRows) Receive() []interface{} {
	*rs = append(*rs, SemesterRow{})
	return (*rs)[len(*rs)-1].Receive()
}

func (t *semesterTable) Select() *dsl.SelectQuery {
	return dsl.
		Select(t.AllColumns()...).From(t)
}

func (t *semesterTable) InsertOneJSON(jsonExpr interface{}) *dsl.InsertQuery {
	return dsl.
		InsertInto(t, t.AllColumns()...).
		Select(
			dsl.Select(
				dsl.Coalesce(`__iv__."id"`, "nextval('wise.semester_id_seq'::regclass)"),
				`__iv__."year"`,
				`__iv__."season"`,
			).
				Fromf(`json_populate_record(null::%s, %s) AS __iv__`, Semester, jsonExpr),
		)
}

func (t *semesterTable) InsertManyJSON(jsonExpr interface{}) *dsl.InsertQuery {
	return dsl.
		InsertInto(t, t.AllColumns()...).
		Select(
			dsl.Select(
				dsl.Coalesce(`__iv__."id"`, "nextval('wise.semester_id_seq'::regclass)"),
				`__iv__."year"`,
				`__iv__."season"`,
			).
				Fromf(`json_populate_recordset(null::%s, %s) AS __iv__`, Semester, jsonExpr),
		)
}

func (t *semesterTable) UpdateJSON(jsonExpr interface{}) *dsl.UpdateQuery {
	return dsl.
		Update(t).
		Set(
			t.ID.Set(dsl.Coalesce(`__ch__."id"`, t.ID)),
			t.Year.Set(dsl.Coalesce(`__ch__."year"`, t.Year)),
			t.Season.Set(dsl.Coalesce(`__ch__."season"`, t.Season)),
		).
		Fromf(`json_populate_record(null::%s, %s) AS __ch__`, Semester, jsonExpr)
}

func (t *semesterTable) DeleteWhere(cond interface{}) *dsl.DeleteQuery {
	return dsl.
		DeleteFrom(t).Where(dsl.WrapExpr(cond))
}
