// Code generated by github.com/hanpama/pgmg. DO NOT EDIT.
package customer_demographics

func Insert(vss ...Values) Query {
	return Query{InsertSQL, []interface{}{string(mustMarshalJSON(vss))}}
}
func InsertReturning(vss ...Values) Query {
	return Query{InsertReturningSQL, []interface{}{string(mustMarshalJSON(vss))}}
}
func Select(k key) Query {
	return k.selectSQL()
}
func Update(k key, args ...attribute) Query {
	return k.updateSQL(args...)
}
func Delete(k key) Query {
	return k.deleteSQL()
}

const (
	InsertSQL = `
		INSERT INTO "customer_demographics"
		SELECT * FROM json_populate_recordset(null::"customer_demographics", $1) `
	InsertReturningSQL = `
		INSERT INTO "customer_demographics"
		SELECT * FROM json_populate_recordset(null::"customer_demographics", $1)
		RETURNING *`
)

func (k PkCustomerDemographics) selectSQL() Query {
	return Query{SelectPkCustomerDemographics, []interface{}{
		k.CustomerTypeID,
	}}
}
func (k PkCustomerDemographics) updateSQL(args ...attribute) Query {
	return Query{UpdatePkCustomerDemographics, []interface{}{
		k.CustomerTypeID,
		string(mustMarshalJSON(Values(args))),
	}}
}
func (k PkCustomerDemographics) deleteSQL() Query {
	return Query{DeletePkCustomerDemographics, []interface{}{
		k.CustomerTypeID,
	}}
}

const (
	SelectPkCustomerDemographics = `
		SELECT * FROM "customer_demographics" WHERE ("customer_demographics"."customer_type_id") = ($1) LIMIT 1
		`
	UpdatePkCustomerDemographics = `
		UPDATE "customer_demographics"
		SET "customer_type_id" = COALESCE(_ch."customer_type_id", "customer_demographics"."customer_type_id"),
			"customer_desc" = COALESCE(_ch."customer_desc", "customer_demographics"."customer_desc")
		FROM (SELECT * FROM json_populate_record(null::"customer_demographics", $2)) _ch
		WHERE ("customer_demographics"."customer_type_id") = ($1)`
	DeletePkCustomerDemographics = `
		DELETE FROM "customer_demographics"
		WHERE ("customer_demographics"."customer_type_id") = ($1)`
)

type key interface {
	selectSQL() Query
	updateSQL(args ...attribute) Query
	deleteSQL() Query
}

type Query struct {
	sql  string
	args []interface{}
}

func (q Query) SQL() string         { return q.sql }
func (q Query) Args() []interface{} { return q.args }
