// Code generated by github.com/hanpama/pgmg. DO NOT EDIT.
package employee_territories

func Insert(vss ...Values) Query {
	return Query{InsertSQL, []interface{}{string(mustMarshalJSON(vss))}}
}
func InsertReturning(vss ...Values) Query {
	return Query{InsertReturningSQL, []interface{}{string(mustMarshalJSON(vss))}}
}
func Select(k key) Query {
	return k.selectSQL()
}
func Update(k key, args ...attribute) Query {
	return k.updateSQL(args...)
}
func Delete(k key) Query {
	return k.deleteSQL()
}

const (
	InsertSQL = `
		INSERT INTO "employee_territories"
		SELECT * FROM json_populate_recordset(null::"employee_territories", $1) `
	InsertReturningSQL = `
		INSERT INTO "employee_territories"
		SELECT * FROM json_populate_recordset(null::"employee_territories", $1)
		RETURNING *`
)

func (k PkEmployeeTerritories) selectSQL() Query {
	return Query{SelectPkEmployeeTerritories, []interface{}{
		k.EmployeeID,
		k.TerritoryID,
	}}
}
func (k PkEmployeeTerritories) updateSQL(args ...attribute) Query {
	return Query{UpdatePkEmployeeTerritories, []interface{}{
		k.EmployeeID,
		k.TerritoryID,
		string(mustMarshalJSON(Values(args))),
	}}
}
func (k PkEmployeeTerritories) deleteSQL() Query {
	return Query{DeletePkEmployeeTerritories, []interface{}{
		k.EmployeeID,
		k.TerritoryID,
	}}
}

const (
	SelectPkEmployeeTerritories = `
		SELECT * FROM "employee_territories" WHERE ("employee_territories"."employee_id", "employee_territories"."territory_id") = ($1, $2) LIMIT 1
		`
	UpdatePkEmployeeTerritories = `
		UPDATE "employee_territories"
		SET "employee_id" = COALESCE(_ch."employee_id", "employee_territories"."employee_id"),
			"territory_id" = COALESCE(_ch."territory_id", "employee_territories"."territory_id")
		FROM (SELECT * FROM json_populate_record(null::"employee_territories", $2)) _ch
		WHERE ("employee_territories"."employee_id", "employee_territories"."territory_id") = ($1, $2)`
	DeletePkEmployeeTerritories = `
		DELETE FROM "employee_territories"
		WHERE ("employee_territories"."employee_id", "employee_territories"."territory_id") = ($1, $2)`
)

type key interface {
	selectSQL() Query
	updateSQL(args ...attribute) Query
	deleteSQL() Query
}

type Query struct {
	sql  string
	args []interface{}
}

func (q Query) SQL() string         { return q.sql }
func (q Query) Args() []interface{} { return q.args }
